[package]
name = "nr"
version = "0.1.0"
edition = "2021"

[lib]
name = "nr"
path = "src/lib.rs"

[[bin]]
name = "nr"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }